# Generated by Django 5.2.1 on 2025-05-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
        ("tracker", "0004_remove_tasks_employees"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="tasks",
            field=models.ManyToManyField(
                blank=True, to="tracker.tasks", verbose_name="Задачи"
            ),
        ),
    ]
