# Generated by Django 5.2.1 on 2025-05-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="employees",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="trackers",
                to="employee.employee",
                verbose_name="Сотрудники",
            ),
        ),
    ]
