# Generated by Django 5.2.1 on 2025-05-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
        ("tracker", "0002_tasks_employees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="employees",
            field=models.ManyToManyField(
                blank=True, null=True, to="employee.employee", verbose_name="Сотрудники"
            ),
        ),
    ]
