# Generated by Django 5.2.1 on 2025-05-15 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_tasks_employees"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasks",
            name="employees",
        ),
    ]
