# Generated by Django 5.2.1 on 2025-05-15 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_remove_tasks_employees"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasks",
            name="related_tracker",
        ),
        migrations.AddField(
            model_name="tasks",
            name="related_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tracker.tasks",
                verbose_name="Связанная родительская задача",
            ),
        ),
    ]
